# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CJModule' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MJRefresh'
  #pod 'KMNavigationBarTransition'
  pod 'YYKit'
  pod 'YTKNetwork'
  pod 'MBProgressHUD'
  pod 'Masonry'
  pod 'DZNEmptyDataSet'
  pod 'DownloadButton'
  pod 'QMUIKit'
  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'FSCalendar'
  pod 'JLRoutes'
  
  
  pod 'CocoaLumberjack'

  # Pods for CommonProject
  
  pod 'UITableView+FDTemplateLayoutCell'


  # Pods for CJModule

end
